# Author: Tugtekin Turan
# E-Mail: tugtekin.turan@iais.fraunhofer.de
# Date: 2023-05-19
# Description: VAD configuration tuned for VBx diarization

name: &name "vad_best_params"

# Path of the evaluation data JSON file
# If not specified, it will be created automatically
dataset: null

# Number of workers to use for processing data
num_workers: 0

# Audio sample rate
sample_rate: 16000

# Whether to generate predictions with overlapping input segments and smoothing filter
gen_overlap_seq: True

# Whether to convert frame level prediction to speech/no-speech segment in start and end times format
gen_seg_table: True

# Whether to write speech segments to a single manifest JSON file
write_to_manifest: True

# Configuration for preparing the manifest
prepare_manifest:

  # Whether to automatically split manifest entry by split_duration to avoid memory issues
  auto_split: True

  # Split duration in seconds (limited to 20/30 secs because more may cause a out-of-memory error)
  split_duration: 30

# Configuration for voice activity detection (VAD)
vad:

  # Path to the VAD model file
  model_path: null

  # Tuned parameters
  parameters:

    # Whether to normalize audio before processing
    normalize_audio: False

    # Window length in seconds for VAD context input
    window_length_in_sec: 0.20

    # Shift length in seconds for generating frame level VAD prediction
    shift_length_in_sec: 0.01

    # Smoothing method for the VAD predictions ("mean" or "median")
    smoothing: "median"

    # Overlap ratio for overlapped mean/median smoothing filter
    overlap: 0.60

    # Post-processing parameters for speech segmentation
    postprocessing:

      # Onset threshold for detecting the beginning and end of a speech segment
      onset: 0.80

      # Offset threshold for detecting the end of a speech segment
      offset: 0.30

      # Adding durations before each speech segment
      pad_onset: 0.20

      # Adding durations after each speech segment
      pad_offset: -0.10

      # Threshold for small non-speech segment deletion
      min_duration_on: 0.30

      # Threshold for short speech segment deletion
      min_duration_off: 0.60

      # Whether to filter speech segments first before applying the post-processing
      filter_speech_first: True

# Path to the temporary manifest JSON file containing the input for VAD
prepared_manifest_vad_input: "./manifest_vad_input.json"

# Output directories for the frame, smoothing, and table outputs
# If not specified, they will be created automatically using default names
frame_out_dir: null
smoothing_out_dir: null
table_out_dir: null

# Output manifest file for speech segments
out_manifest_filepath: null
